[package]
name = "scaffed"
version = "0.1.0"
edition = "2024"

[lib]
name = "scaffer"
path = "src/lib.rs"

[dependencies]
promkit = "0.7.0"
reqwest = { version = "0.12.12", features = ["blocking"] }
zip = "2.2.3"
